"""corrigiendo

Revision ID: 5c9310f877ad
Revises: 7bd3e2189ac4
Create Date: 2024-10-07 10:30:41.546849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c9310f877ad'
down_revision = '7bd3e2189ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estudiante_id', sa.Integer(), nullable=True))
        batch_op.alter_column('contenido',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('curso_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['estudiante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('curso_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('contenido',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('estudiante_id')
        batch_op.drop_column('nota')

    # ### end Alembic commands ###
