"""Add contenido column to Examen

Revision ID: 7bd3e2189ac4
Revises: dfd93eb84323
Create Date: 2024-10-07 10:00:02.211168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bd3e2189ac4'
down_revision = 'dfd93eb84323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=False))
        batch_op.drop_column('nota')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nota', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###
