"""Eliminar Estudiante y ajustar relación con usuarios

Revision ID: db6acd0d8807
Revises: 2314d1a027c6
Create Date: 2024-10-03 11:13:27.112741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db6acd0d8807'
down_revision = '2314d1a027c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estudiante_curso')
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('estudiante')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiante',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('estudiante_curso',
    sa.Column('estudiante_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('curso_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name='estudiante_curso_ibfk_2'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], name='estudiante_curso_ibfk_1'),
    sa.PrimaryKeyConstraint('estudiante_id', 'curso_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
