"""Eliminar relación duplicada entre User y Curso

Revision ID: ef0dce7ac350
Revises: db6acd0d8807
Create Date: 2024-10-03 11:21:16.473916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef0dce7ac350'
down_revision = 'db6acd0d8807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint('curso_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('curso_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
